scoreboard players set @p FiveSecondLoop 0

execute @p[score_InGameDays_min=0,score_InGameDays=0] ~ ~ ~ function days:day1
execute @p[score_InGameDays_min=1,score_InGameDays=1] ~ ~ ~ function days:day2
execute @p[score_InGameDays_min=2,score_InGameDays=2] ~ ~ ~ function days:day3
execute @p[score_InGameDays_min=3,score_InGameDays=3] ~ ~ ~ function days:day4
execute @p[score_InGameDays_min=4,score_InGameDays=4] ~ ~ ~ function days:day5
execute @p[score_InGameDays_min=5,score_InGameDays=5] ~ ~ ~ function days:day6
execute @p[score_InGameDays_min=6,score_InGameDays=6] ~ ~ ~ function days:day7
execute @p[score_InGameDays_min=7,score_InGameDays=7] ~ ~ ~ function days:day8
execute @p[score_InGameDays_min=8,score_InGameDays=8] ~ ~ ~ function days:day9
execute @p[score_InGameDays_min=9,score_InGameDays=9] ~ ~ ~ function days:day10
execute @p[score_InGameDays_min=10,score_InGameDays=10] ~ ~ ~ function days:day11
execute @p[score_InGameDays_min=11,score_InGameDays=11] ~ ~ ~ function days:day12
execute @p[score_InGameDays_min=12,score_InGameDays=12] ~ ~ ~ function days:day13
execute @p[score_InGameDays_min=13,score_InGameDays=13] ~ ~ ~ function days:day14
execute @p[score_InGameDays_min=14,score_InGameDays=14] ~ ~ ~ function days:day15
execute @p[score_InGameDays_min=15,score_InGameDays=15] ~ ~ ~ function days:day16
execute @p[score_InGameDays_min=16,score_InGameDays=16] ~ ~ ~ function days:day17
execute @p[score_InGameDays_min=17,score_InGameDays=17] ~ ~ ~ function days:day18
execute @p[score_InGameDays_min=18,score_InGameDays=18] ~ ~ ~ function days:day19
execute @p[score_InGameDays_min=19,score_InGameDays=19] ~ ~ ~ function days:day20
execute @p[score_InGameDays_min=20,score_InGameDays=20] ~ ~ ~ function days:day21
execute @p[score_InGameDays_min=21,score_InGameDays=21] ~ ~ ~ function days:day22
execute @p[score_InGameDays_min=22,score_InGameDays=22] ~ ~ ~ function days:day23
execute @p[score_InGameDays_min=23,score_InGameDays=23] ~ ~ ~ function days:day24
execute @p[score_InGameDays_min=24,score_InGameDays=24] ~ ~ ~ function days:day25
execute @p[score_InGameDays_min=25,score_InGameDays=25] ~ ~ ~ function days:day26
execute @p[score_InGameDays_min=26,score_InGameDays=26] ~ ~ ~ function days:day27
execute @p[score_InGameDays_min=27,score_InGameDays=27] ~ ~ ~ function days:day28
execute @p[score_InGameDays_min=28,score_InGameDays=28] ~ ~ ~ function days:day29
execute @p[score_InGameDays_min=29,score_InGameDays=29] ~ ~ ~ function days:day30
execute @p[score_InGameDays_min=30,score_InGameDays=30] ~ ~ ~ function days:day31
execute @p[score_InGameDays_min=31,score_InGameDays=31] ~ ~ ~ function days:day32
execute @p[score_InGameDays_min=32,score_InGameDays=32] ~ ~ ~ function days:day33
execute @p[score_InGameDays_min=33,score_InGameDays=33] ~ ~ ~ function days:day34
execute @p[score_InGameDays_min=34,score_InGameDays=34] ~ ~ ~ function days:day35
execute @p[score_InGameDays_min=35,score_InGameDays=35] ~ ~ ~ function days:day36
execute @p[score_InGameDays_min=36,score_InGameDays=36] ~ ~ ~ function days:day37
execute @p[score_InGameDays_min=37,score_InGameDays=37] ~ ~ ~ function days:day38
execute @p[score_InGameDays_min=38,score_InGameDays=38] ~ ~ ~ function days:day39
execute @p[score_InGameDays_min=39,score_InGameDays=39] ~ ~ ~ function days:day40
execute @p[score_InGameDays_min=40,score_InGameDays=40] ~ ~ ~ function days:day41
execute @p[score_InGameDays_min=41,score_InGameDays=41] ~ ~ ~ function days:day42
execute @p[score_InGameDays_min=42,score_InGameDays=42] ~ ~ ~ function days:day43
execute @p[score_InGameDays_min=43,score_InGameDays=43] ~ ~ ~ function days:day44
execute @p[score_InGameDays_min=44,score_InGameDays=44] ~ ~ ~ function days:day45
execute @p[score_InGameDays_min=45,score_InGameDays=45] ~ ~ ~ function days:day46
execute @p[score_InGameDays_min=46,score_InGameDays=46] ~ ~ ~ function days:day47
execute @p[score_InGameDays_min=47,score_InGameDays=47] ~ ~ ~ function days:day48
execute @p[score_InGameDays_min=48,score_InGameDays=48] ~ ~ ~ function days:day49
execute @p[score_InGameDays_min=49,score_InGameDays=49] ~ ~ ~ function days:day50
execute @p[score_InGameDays_min=50,score_InGameDays=50] ~ ~ ~ function days:day51
execute @p[score_InGameDays_min=51,score_InGameDays=51] ~ ~ ~ function days:day52
execute @p[score_InGameDays_min=52,score_InGameDays=52] ~ ~ ~ function days:day53
execute @p[score_InGameDays_min=53,score_InGameDays=53] ~ ~ ~ function days:day54
execute @p[score_InGameDays_min=54,score_InGameDays=54] ~ ~ ~ function days:day55
execute @p[score_InGameDays_min=55,score_InGameDays=55] ~ ~ ~ function days:day56
execute @p[score_InGameDays_min=56,score_InGameDays=56] ~ ~ ~ function days:day57
execute @p[score_InGameDays_min=57,score_InGameDays=57] ~ ~ ~ function days:day58
execute @p[score_InGameDays_min=58,score_InGameDays=58] ~ ~ ~ function days:day59
execute @p[score_InGameDays_min=59,score_InGameDays=59] ~ ~ ~ function days:day60
execute @p[score_InGameDays_min=60,score_InGameDays=60] ~ ~ ~ function days:day61
execute @p[score_InGameDays_min=61,score_InGameDays=61] ~ ~ ~ function days:day62
execute @p[score_InGameDays_min=62,score_InGameDays=62] ~ ~ ~ function days:day63
execute @p[score_InGameDays_min=63,score_InGameDays=63] ~ ~ ~ function days:day64
execute @p[score_InGameDays_min=64,score_InGameDays=64] ~ ~ ~ function days:day65
execute @p[score_InGameDays_min=65,score_InGameDays=65] ~ ~ ~ function days:day66
execute @p[score_InGameDays_min=66,score_InGameDays=66] ~ ~ ~ function days:day67
execute @p[score_InGameDays_min=67,score_InGameDays=67] ~ ~ ~ function days:day68
execute @p[score_InGameDays_min=68,score_InGameDays=68] ~ ~ ~ function days:day69
execute @p[score_InGameDays_min=69,score_InGameDays=69] ~ ~ ~ function days:day70
execute @p[score_InGameDays_min=70,score_InGameDays=70] ~ ~ ~ function days:day71
execute @p[score_InGameDays_min=71,score_InGameDays=71] ~ ~ ~ function days:day72
execute @p[score_InGameDays_min=72,score_InGameDays=72] ~ ~ ~ function days:day73
execute @p[score_InGameDays_min=73,score_InGameDays=73] ~ ~ ~ function days:day74
execute @p[score_InGameDays_min=74,score_InGameDays=74] ~ ~ ~ function days:day75
execute @p[score_InGameDays_min=75,score_InGameDays=75] ~ ~ ~ function days:day76
execute @p[score_InGameDays_min=76,score_InGameDays=76] ~ ~ ~ function days:day77
execute @p[score_InGameDays_min=77,score_InGameDays=77] ~ ~ ~ function days:day78
execute @p[score_InGameDays_min=78,score_InGameDays=78] ~ ~ ~ function days:day79
execute @p[score_InGameDays_min=79,score_InGameDays=79] ~ ~ ~ function days:day80
execute @p[score_InGameDays_min=80,score_InGameDays=80] ~ ~ ~ function days:day81
execute @p[score_InGameDays_min=81,score_InGameDays=81] ~ ~ ~ function days:day82
execute @p[score_InGameDays_min=82,score_InGameDays=82] ~ ~ ~ function days:day83
execute @p[score_InGameDays_min=83,score_InGameDays=83] ~ ~ ~ function days:day84
execute @p[score_InGameDays_min=84,score_InGameDays=84] ~ ~ ~ function days:day85
execute @p[score_InGameDays_min=85,score_InGameDays=85] ~ ~ ~ function days:day86
execute @p[score_InGameDays_min=86,score_InGameDays=86] ~ ~ ~ function days:day87
execute @p[score_InGameDays_min=87,score_InGameDays=87] ~ ~ ~ function days:day88
execute @p[score_InGameDays_min=88,score_InGameDays=88] ~ ~ ~ function days:day89
execute @p[score_InGameDays_min=89,score_InGameDays=89] ~ ~ ~ function days:day90
execute @p[score_InGameDays_min=90,score_InGameDays=90] ~ ~ ~ function days:day91
execute @p[score_InGameDays_min=91,score_InGameDays=91] ~ ~ ~ function days:day92
execute @p[score_InGameDays_min=92,score_InGameDays=92] ~ ~ ~ function days:day93
execute @p[score_InGameDays_min=93,score_InGameDays=93] ~ ~ ~ function days:day94
execute @p[score_InGameDays_min=94,score_InGameDays=94] ~ ~ ~ function days:day95
execute @p[score_InGameDays_min=95,score_InGameDays=95] ~ ~ ~ function days:day96
execute @p[score_InGameDays_min=96,score_InGameDays=96] ~ ~ ~ function days:day97
execute @p[score_InGameDays_min=97,score_InGameDays=97] ~ ~ ~ function days:day98
execute @p[score_InGameDays_min=98,score_InGameDays=98] ~ ~ ~ function days:day99
execute @p[score_InGameDays_min=99,score_InGameDays=99] ~ ~ ~ function days:day100
